[
    {
        "WfName": "workshopproposal",
        "AcessPermission": "Private", 
        "AuthGroups": ["Berger Portal Owners"],
        "AuthUsersADId": [103, 174, 151, 21, 201],
        "AuthUsersEmpId": [1270, 334],  
        "DisplayTxt": "Workshop Proposal Dashboard",
        "ViewUrl": { "siteUrl": "leaveauto/_layouts/15/WorkshopProposal.aspx?WP=", "qryStrKeyTyp": "GUID", "mode": "&mode=read", "titleTag": "WP-" },
        "MasterListInfo": { "name": "WorkshopProposalMaster", "select": "GUID,ID,Title,Created,Modified,Author/ID,Author/Title,Author/Office,Author/JobTitle,Status,EmployeeID,PendingWith/ID,PendingWith/Title&$expand=Author/ID,PendingWith/ID&$orderby=Created desc", "primaryKey": "Title"},
        "RenderDetListInfo": [{ "name": "WorkshopProposalInfo", "select": "ID,Title,Created,Modified,Author/ID,Author/Title,Author/Office,Author/JobTitle,ExpectedDate,WorkshopLocation,ExpectedParticipant,Purpose,TotalAmount,GLCode,CostCenter,IONumber,FoodCost,HallOrVenueRent,PromotionalItem,DecorationCost,OtherCost,BudgetedExpenditure,ActualLocation,ActualParticipant,ActualFoodCost,ActualDecorationCost,ActualHallOrVenueRent,ActualPromotionalItem,ActualExpenditure,ActualOtherCost"}],
        "DetailsListInfo": [{ "name": "WorkshopProposalInfo", "select": "ID,Title,Created,Modified,Author/ID,Author/Title,Author/Office,Author/JobTitle,ExpectedDate,WorkshopLocation,ExpectedParticipant,Purpose,TotalAmount,GLCode,CostCenter,IONumber,FoodCost,HallOrVenueRent,PromotionalItem,DecorationCost,OtherCost,BudgetedExpenditure,ActualLocation,ActualParticipant,ActualFoodCost,ActualDecorationCost,ActualHallOrVenueRent,ActualPromotionalItem,ActualExpenditure,ActualOtherCost&$expand=Author/ID&$orderby=Created desc", "primaryKey": "Title"}],
        "DbViewColDef": [
            { "fldType": "ViewLinkIdField", "headerName": "Action", "field": "Title", "editable":false, "minWidth": 100, "siteUrl": "leaveauto/_layouts/15/ColorBankProcess/ColorBankProcess.aspx?CBP=", "qryStrKeyTyp": "ID", "mode": "&mode=read"},
            { "fldType": "ViewOnTitleIdField", "headerName": "RequestID", "field": "Title", "editable":false, "minWidth": 120, "siteUrl": "leaveauto/_layouts/15/ColorBankProcess/ColorBankProcess.aspx?CBP=", "qryStrKeyTyp": "ID", "mode": "&mode=read"},
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "editable":false, "minWidth": 140 },
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "EmployeeId", "field": "EmployeeID", "editable":true, "minWidth": 140, "hide":true },
            { "fldType": "TextField", "headerName": "Requestor JobTitle", "field": "Author.JobTitle", "editable":false, "minWidth": 200, "hide":true },
            { "fldType": "TextField", "headerName": "CustomerID", "field": "CustomerID", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "CustomerName", "field": "CustomerName", "editable":true, "minWidth": 250 },
            { "fldType": "TextField", "headerName": "Address", "field": "Address", "editable":true, "minWidth": 250 },
            { "fldType": "TextField", "headerName": "Territory", "field": "Territory", "editable":true, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "ContactNo", "field": "ContactNo", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "AccountGroup", "field": "AccountGroup", "editable":true, "minWidth": 150 },
            { "fldType": "TextField", "headerName": "ProprietorName", "field": "ProprietorName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "FatherName", "field": "FatherName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "DealerAddress", "field": "DealerAddress", "editable":true, "minWidth": 300 },
            { "fldType": "GetSetDateField", "headerName": "Installation Date", "field": "DateInstallation", "valueGetter":"DateInstallation", "editable":false, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "PaymentMode", "field": "PaymentMode", "editable":true, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "Amount", "field": "Amount", "editable":true, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "DownPayment", "field": "DownPayment", "editable":true, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "MonthlyInstallment", "field": "MonthlyIns", "editable":true, "minWidth": 180 },
            { "fldType": "TextField", "headerName": "NoOfIns", "field": "NoOfInstallment", "editable":true, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "SubsidyAmount", "field": "SubsidyAmount", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "SAPAssetNumber", "field": "SAPAssetNumber", "editable":true, "minWidth": 165 },
            { "fldType": "GetSetDateField", "headerName": "DATEOFINSTALLATION", "field": "DATEOFINSTALLATION", "valueGetter":"DATEOFINSTALLATION", "editable":false, "minWidth": 200 },
            { "fldType": "TextField", "headerName": "SPMONFORSAP", "field": "SPMONFORSAP", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "ANLHTXT", "field": "ANLHTXT", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "PartialMachineName", "field": "PartialMachineName", "editable":true, "minWidth": 300 }
        ],
        "MasterDetailViewColDef": [
            { "fldType": "ViewLinkIdField", "headerName": "Action", "field": "Title", "editable":false, "minWidth": 100, "siteUrl": "leaveauto/_layouts/15/ColorBankProcess/ColorBankProcess.aspx?CBP=", "qryStrKeyTyp": "ID", "mode": "&mode=read"},
            { "fldType": "ViewOnTitleIdField", "headerName": "RequestID", "field": "Title", "editable":false, "minWidth": 120, "siteUrl": "leaveauto/_layouts/15/ColorBankProcess/ColorBankProcess.aspx?CBP=", "qryStrKeyTyp": "ID", "mode": "&mode=read"},
            { "fldType": "GetSetDateField", "headerName": "Created", "field": "Created", "valueGetter":"Created", "editable":false, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "Requested by", "field": "Author.Title", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Office", "field": "Author.Office", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "EmployeeId", "field": "EmployeeID", "editable":true, "minWidth": 140, "hide":true },
            { "fldType": "TextField", "headerName": "Requestor JobTitle", "field": "Author.JobTitle", "editable":false, "minWidth": 200, "hide":true },
            { "fldType": "TextField", "headerName": "CustomerID", "field": "CustomerID", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "CustomerName", "field": "CustomerName", "editable":true, "minWidth": 250 },
            { "fldType": "TextField", "headerName": "Address", "field": "Address", "editable":true, "minWidth": 250 },
            { "fldType": "TextField", "headerName": "Territory", "field": "Territory", "editable":true, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "ContactNo", "field": "ContactNo", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "AccountGroup", "field": "AccountGroup", "editable":true, "minWidth": 150 },
            { "fldType": "TextField", "headerName": "ProprietorName", "field": "ProprietorName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "FatherName", "field": "FatherName", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "DealerAddress", "field": "DealerAddress", "editable":true, "minWidth": 300 },
            { "fldType": "GetSetDateField", "headerName": "Installation Date", "field": "DateInstallation", "valueGetter":"DateInstallation", "editable":false, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "PaymentMode", "field": "PaymentMode", "editable":true, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "Amount", "field": "Amount", "editable":true, "minWidth": 120 },
            { "fldType": "TextField", "headerName": "DownPayment", "field": "DownPayment", "editable":true, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "MonthlyInstallment", "field": "MonthlyIns", "editable":true, "minWidth": 180 },
            { "fldType": "TextField", "headerName": "NoOfIns", "field": "NoOfInstallment", "editable":true, "minWidth": 160 },
            { "fldType": "TextField", "headerName": "SubsidyAmount", "field": "SubsidyAmount", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "SAPAssetNumber", "field": "SAPAssetNumber", "editable":true, "minWidth": 165 },
            { "fldType": "GetSetDateField", "headerName": "DATEOFINSTALLATION", "field": "DATEOFINSTALLATION", "valueGetter":"DATEOFINSTALLATION", "editable":false, "minWidth": 200 },
            { "fldType": "TextField", "headerName": "SPMONFORSAP", "field": "SPMONFORSAP", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "ANLHTXT", "field": "ANLHTXT", "editable":true, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "PartialMachineName", "field": "PartialMachineName", "editable":true, "minWidth": 300 },
            { "fldType": "TextField", "headerName": "Pending With", "field": "PendingWith.Title", "editable":false, "minWidth": 140 },
            { "fldType": "TextField", "headerName": "Status", "field": "Status", "editable":true, "minWidth": 165 },                            
            { "fldType": "TextField", "headerName": "Ready Made SalesType", "field": "ReadySalesType", "editable":false, "minWidth": 250 },
            { "fldType": "NumberField", "headerName": "Ready PermonthFirst", "field": "ReadyPermonthFirst", "editable":false, "minWidth": 200 },
            { "fldType": "NumberField", "headerName": "Ready PerMonth2nd", "field": "ReadyPerMonth2nd", "editable":false, "minWidth": 200 },
            { "fldType": "TextField", "headerName": "Tinting SalesType", "field": "TinSalesType", "valueGetter":"ShkEndDate", "editable":false, "minWidth": 200 },
            { "fldType": "NumberField", "headerName": "Tinting PermonthFirst", "field": "TinPermonthFirst", "editable":false, "minWidth": 200 },
            { "fldType": "NumberField", "headerName": "Tinting PerMonth2nd", "field": "TinPerMonth2nd", "editable":false, "minWidth": 200 },
            { "fldType": "TextField", "headerName": "CB Bases-Colorants SalesType", "field": "CBCSalesType", "editable":false, "minWidth": 250 },            
            { "fldType": "NumberField", "headerName": "CBC PermonthFirst", "field": "CBCPermonthFirst", "editable":false, "minWidth": 200 },            
            { "fldType": "NumberField", "headerName": "CBC PerMonth2nd", "field": "CBCPerMonth2nd", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Computer Type", "field": "ComEquipmentType", "editable":false, "minWidth": 180 },
            { "fldType": "TextField", "headerName": "Computer Description", "field": "ComDescription", "editable":false, "minWidth": 250 },
            { "fldType": "NumberField", "headerName": "Computer AssetValue", "field": "ComAssetValue", "editable":false, "minWidth": 200 },
            { "fldType": "NumberField", "headerName": "Computer AmountTk", "field": "ComAmountTk", "editable":false, "minWidth": 200 },
            { "fldType": "GetSetDateField", "headerName": "Computer EndDate", "field": "ComEndDate", "valueGetter":"ComEndDate", "editable":false, "minWidth": 190 },
            { "fldType": "NumberField", "headerName": "Computer GallonQty", "field": "ComGallonQty", "editable":false, "minWidth": 180 },
            { "fldType": "TextField", "headerName": "Tinting EquipmentType", "field": "TinEquipmentType", "editable":false, "minWidth": 220 },
            { "fldType": "TextField", "headerName": "Tinting Description", "field": "TinDescription", "editable":false, "minWidth": 250 },
            { "fldType": "NumberField", "headerName": "Tinting AssetValue", "field": "TinAssetValue", "editable":false, "minWidth": 190 },
            { "fldType": "NumberField", "headerName": "Tinting AmountTk", "field": "TinAmountTk", "editable":false, "minWidth": 180 },
            { "fldType": "GetSetDateField", "headerName": "Tinting EndDate", "field": "TinEndDate", "valueGetter":"TinEndDate", "editable":false, "minWidth": 180 },
            { "fldType": "NumberField", "headerName": "Tinting GallonQty", "field": "TinGallonQty", "editable":false, "minWidth": 165 },
            { "fldType": "TextField", "headerName": "Shaker Type", "field": "ShkEquipmentType", "editable":false, "minWidth": 180 },
            { "fldType": "TextField", "headerName": "Shaker Description", "field": "ShkDescription", "editable":false, "minWidth": 250 },
            { "fldType": "NumberField", "headerName": "Shaker AssetValue", "field": "ShkAssetValue", "editable":false, "minWidth": 165 },
            { "fldType": "NumberField", "headerName": "Shaker AmountTk", "field": "ShkAmountTk", "editable":false, "minWidth": 165 },
            { "fldType": "GetSetDateField", "headerName": "Shaker EndDate", "field": "ShkEndDate", "valueGetter":"ShkEndDate", "editable":false, "minWidth": 170 },
            { "fldType": "NumberField", "headerName": "Shaker GallonQty", "field": "ShkGallonQty", "editable":false, "minWidth": 165 }
        ]
    }
 
]
